version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  public-api:
    image: benlewsey27/qrcode-generator-public-api:0.2.0
    container_name: qrcode-generator-public-api
    build: src/public-api
    environment:
      - DEBUG=1
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=qrcode-generator
      - KAFKA_PARTITIONS=4
    ports:
      - 8000:8000
